### ISSUE TITLE
build error. Fix this issue.

### ISSUE THREAD

**Issue by israfilbd** [Evolution-XYZ/manifest#9]
Starting ninja...
FAILED: ninja: 'out/target/product/RMX1901/obj/EXECUTABLES/updater_intermediates/updater', needed by 'out/target/product/RMX1901/obj/PACKAGING/target_files_intermediates/lineage_RMX1901-target_files.zip.list', missing and no known rule to make it
05:46:49 ninja failed with: exit status 1

#### failed to build some targets (25 seconds) ####

------------------------------------------------------------------------
Build Failed: returned 1

**Comment by ij-israfil** [comment]
I got the fixes.
deprecated-ota missing 
Add this: https://github.com/LineageOS/android_bootable_deprecated-ota

**Comment by israfilbd** [comment]
I got the fixes. 
Deprecated-ota missing 
Include this: https://github.com/LineageOS/android_bootable_deprecated-ota
